language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - build-tools-29.0.2
    - android-28
    
before_install:
   - pwd
   - ls -la
   - chmod +x gradlew
script:
    - ./gradlew test build connectedCheck --status --stacktrace
